/* wusbmote: Wiimote accessory to USB Adapter
 * Copyright (C) 2012-2014 Raphaël Assénat
 *
 * Based on:
 *   VBoy2USB: Virtual Boy controller to USB Adapter
 *   Copyright (C) 2009 Raphaël Assénat
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * The author may be contacted at raph@raphnet.net
 */
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/pgmspace.h>
#include <avr/wdt.h>
#include <avr/sleep.h>
#include <util/delay.h>
#include <string.h>

#include "usbdrv.h"
#include "gamepad.h"
#include "eeprom.h"
#include "config.h"
#include "wusbmote_requests.h"

#include "i2c_gamepad.h"
#include "i2c_mouse.h"

static uchar const *rt_usbHidReportDescriptor=NULL;
static uchar rt_usbHidReportDescriptorSize=0;
static uchar const *rt_usbDeviceDescriptor=NULL;
static uchar rt_usbDeviceDescriptorSize=0;


char usbDescriptorConfiguration[] = { 0 }; // dummy

uchar my_usbDescriptorConfiguration[] = {    /* USB configuration descriptor */
    9,          /* sizeof(usbDescriptorConfiguration): length of descriptor in bytes */
    USBDESCR_CONFIG,    /* descriptor type */
    18 + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT + 9, 0,
                /* total length of data returned (including inlined descriptors) */
    1,          /* number of interfaces in this configuration */
    1,          /* index of this configuration */
    0,          /* configuration name string index */
#if USB_CFG_IS_SELF_POWERED
    USBATTR_SELFPOWER,  /* attributes */
#else
    USBATTR_BUSPOWER,   /* attributes */
#endif
    USB_CFG_MAX_BUS_POWER/2,            /* max USB current in 2mA units */
/* interface descriptor follows inline: */
    9,          /* sizeof(usbDescrInterface): length of descriptor in bytes */
    USBDESCR_INTERFACE, /* descriptor type */
    0,          /* index of this interface */
    0,          /* alternate setting for this interface */
    USB_CFG_HAVE_INTRIN_ENDPOINT,   /* endpoints excl 0: number of endpoint descriptors to follow */
    USB_CFG_INTERFACE_CLASS,
    USB_CFG_INTERFACE_SUBCLASS,
    USB_CFG_INTERFACE_PROTOCOL,
    0,          /* string index for interface */
//#if (USB_CFG_DESCR_PROPS_HID & 0xff)    /* HID descriptor */
    9,          /* sizeof(usbDescrHID): length of descriptor in bytes */
    USBDESCR_HID,   /* descriptor type: HID */
    0x01, 0x01, /* BCD representation of HID version */
    0x00,       /* target country code */
    0x01,       /* number of HID Report (or other HID class) Descriptor infos to follow */
    0x22,       /* descriptor type: report */
    USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH, 0,  /* total length of report descriptor */
//#endif
#if USB_CFG_HAVE_INTRIN_ENDPOINT    /* endpoint descriptor for endpoint 1 */
    7,          /* sizeof(usbDescrEndpoint) */
    USBDESCR_ENDPOINT,  /* descriptor type = endpoint */
    0x81,       /* IN endpoint number 1 */
    0x03,       /* attrib: Interrupt endpoint */
    8, 0,       /* maximum packet size */
    USB_CFG_INTR_POLL_INTERVAL, /* in ms */
#endif
};

static Gamepad *curGamepad;

/* ----------------------- hardware I/O abstraction ------------------------ */

static void hardwareInit(void)
{
	// init port C as input with pullup on all but SCL/SDA pins. Those are external to 3.3v
	DDRC = 0x00;
	PORTC = 0x0f;

	// Port B does nothing in this project
	DDRB = 0x00;
	PORTB = 0xff;

	/*
	 * For port D, activate pull-ups on all lines except the D+, D- and bit 1.
	 *
	 * For historical reasons (a mistake on an old PCB), bit 1
	 * is now always connected with bit 0. So bit 1 configured
	 * as an input without pullup.
	 *
	 * Usb pin are init as output, low. (device reset). They are released
	 * later when usbReset() is called.
	 */
	PORTD = 0xf8;
	DDRD = 0x01 | 0x04;

	/* Configure timers */
	/* configure timer 0 for a rate of 12M/(1024 * 256) = 45.78 Hz (~22ms) */
	TCCR0 = 5;      /* timer 0 prescaler: 1024 */

	TCCR2 = (1<<WGM21)|(1<<CS22)|(1<<CS21)|(1<<CS20);
	OCR2 = 196; // for 60 hz
}

static void usbReset(void)
{
	/* [...] a single ended zero or SE0 can be used to signify a device
	   reset if held for more than 10mS. A SE0 is generated by holding
       both th D- and D+ low (< 0.3V).
	*/
	PORTD &= ~(0x01 | 0x04); // Set D+ and D- to 0
	DDRD |= 0x01 | 0x04;
	_delay_ms(15);
	DDRD &= ~(0x01 | 0x04);
}
static uchar    reportBuffer[10];    /* buffer for HID reports */

/* ------------------------------------------------------------------------- */
/* ----------------------------- USB interface ----------------------------- */
/* ------------------------------------------------------------------------- */

static uchar    idleRate;           /* in 4 ms units */

uchar	usbFunctionDescriptor(struct usbRequest *rq)
{
	switch(rq->bmRequestType & USBRQ_TYPE_MASK)
	{
		case USBRQ_TYPE_STANDARD:
			if (rq->bRequest == USBRQ_GET_DESCRIPTOR)
			{
				// USB spec 9.4.3, high byte is descriptor type
				switch (rq->wValue.bytes[1])
				{
					case USBDESCR_DEVICE:
						usbMsgPtr = (void*)rt_usbDeviceDescriptor;
						return rt_usbDeviceDescriptorSize;
					case USBDESCR_HID_REPORT:
						usbMsgPtr = (void*)rt_usbHidReportDescriptor;
						return rt_usbHidReportDescriptorSize;
					case USBDESCR_CONFIG:
						usbMsgPtr = my_usbDescriptorConfiguration;
						return sizeof(my_usbDescriptorConfiguration);
				}
			}
			break;

		case USBRQ_TYPE_VENDOR:
			break;

	}

	return 0;
}

uchar	usbFunctionSetup(uchar data[8])
{
	uchar rqdata[4];
	static uchar replybuf[8];
	usbRequest_t    *rq = (void *)data;

	usbMsgPtr = reportBuffer;

	switch (rq->bmRequestType & USBRQ_TYPE_MASK)
	{
		case USBRQ_TYPE_CLASS:
			if(rq->bRequest == USBRQ_HID_GET_REPORT){  /* wValue: ReportType (highbyte), ReportID (lowbyte) */
				/* we only have one report type, so don't look at wValue */
				curGamepad->buildReport(reportBuffer);
				return curGamepad->report_size;
			}else if(rq->bRequest == USBRQ_HID_GET_IDLE){
				usbMsgPtr = &idleRate;
				return 1;
			}else if(rq->bRequest == USBRQ_HID_SET_IDLE){
				idleRate = rq->wValue.bytes[1];
			}
			break;

		case USBRQ_TYPE_VENDOR:
			rqdata[0] = rq->wValue.bytes[0];
			rqdata[1] = rq->wValue.bytes[1];
			rqdata[2] = rq->wIndex.bytes[0];
			rqdata[3] = rq->wIndex.bytes[1];
			replybuf[0] = rq->bRequest;
			usbMsgPtr = replybuf;

			switch (rq->bRequest)
			{
				case RQ_WUSBMOTE_SETSERIAL:
					config_set_serial((char*)rqdata);
					return 1;
			}
			break;
	}
	return 0;
}

/* ------------------------------------------------------------------------- */

void transferGamepadReport(void)
{
	int i;
	int todo = curGamepad->report_size;

	curGamepad->buildReport(reportBuffer);

	for (i=0; i<=curGamepad->report_size; i+=8)
	{
		usbSetInterrupt(reportBuffer + i, todo > 8 ? 8 : todo);
		while (!usbInterruptIsReady()) {
			usbPoll(); wdt_reset();
		}
		todo -= 8;
	}
}

int main(void)
{
	char must_report = 0, first_run = 1;
	uchar   idleCounter = 0;

	hardwareInit();
	eeprom_init();

	g_eeprom_data.cfg.mode = CFG_MODE_MOUSE;
	switch (g_eeprom_data.cfg.mode)
	{
		default:
			g_eeprom_data.cfg.mode = CFG_MODE_JOYSTICK;
			eeprom_commit();
			// fallthrough to Joystick mode
		case CFG_MODE_JOYSTICK:
			curGamepad = i2cGamepad_GetGamepad();
			break;

		case CFG_MODE_MOUSE:
			curGamepad = i2cMouse_GetGamepad();
			break;
	}

	// configure report descriptor according to
	// the current gamepad
	rt_usbHidReportDescriptor = curGamepad->reportDescriptor;
	rt_usbHidReportDescriptorSize = curGamepad->reportDescriptorSize;
	rt_usbDeviceDescriptor = (void*)curGamepad->deviceDescriptor;
	rt_usbDeviceDescriptorSize = curGamepad->deviceDescriptorSize;

	// patch the config descriptor with the HID report descriptor size
	my_usbDescriptorConfiguration[25] = rt_usbHidReportDescriptorSize;
	my_usbDescriptorConfiguration[26] = rt_usbHidReportDescriptorSize >> 8;

	//wdt_enable(WDTO_2S);
	curGamepad->init();

	usbReset();
	usbInit();
	sei();

	for(;;){	/* main event loop */
		wdt_reset();

		// this must be called at each 50 ms or less
		usbPoll();

		if (first_run) {
			curGamepad->update();
			first_run = 0;
		}

		if(TIFR & (1<<TOV0)){   /* 22 ms timer */
			TIFR = 1<<TOV0;
			if(idleRate != 0){
				if(idleCounter > 4){
					idleCounter -= 5;   /* 22 ms in units of 4 ms */
				}else{
					idleCounter = idleRate;
					must_report = 1;
				}
			}
		}

		if (TIFR & (1<<OCF2))
		{
			TIFR = 1<<OCF2;
			if (!must_report)
			{
				sleep_enable();
				sleep_cpu();
				sleep_disable();
				_delay_us(100);

				curGamepad->update();
				if (curGamepad->changed()) {
					must_report = 1;
				}
			}

		}

		if(must_report && usbInterruptIsReady())
		{
			transferGamepadReport();
			must_report = 0;
		}
	}
	return 0;
}
